"""Metric sweeps over an algorithm parameter, e.g. the layer count of a QAOA."""

from __future__ import annotations

from typing import TYPE_CHECKING

from luna_bench.custom import plot
from luna_bench.metrics import ApproximationRatio, Runtime
from luna_bench.plots.dimensions import MetricDimension
from luna_bench.plots.generics.parameter_sweep_plot import ParameterSweepPlot
from luna_bench.plots.plot_style import Figure

if TYPE_CHECKING:
    from luna_bench.plots.plot_style import ErrorBars, PlotStyle
    from luna_bench.plots.utils import Aggregation


@plot(ApproximationRatio)
class ApproximationRatioVsParameterPlot(ParameterSweepPlot):
    """Approximation ratio against a swept algorithm parameter, one line per model.

    The plot for "does another QAOA layer buy anything": add one algorithm entry per
    value of the parameter, and the sweep shows how close to the optimum each of them
    got. ``1.0`` - marked by the reference line - is the optimum.

    Requires the ``ApproximationRatio`` metric.

    Every display option is inherited and can be set when the plot is constructed,
    e.g. ``ApproximationRatioVsParameterPlot(parameter="layers", hue=None)``.
    `ParameterSweepPlot` documents the sweep itself; `SeabornPlot` the figure size and
    the output formats.

    Attributes
    ----------
    parameter : str
        Attribute of the algorithm configuration that is swept, by default ``"reps"``.
    figure_filename : str
        Stem of the written figure files, by default ``"approximation_ratio_vs_parameter"``.

    Examples
    --------
    >>> for layers in (1, 2, 3, 4):
    ...     bench.add_algorithm(f"qaoa_p{layers}", QAOA(reps=layers))
    >>> bench.add_metric(name="approx_ratio", metric=ApproximationRatio())
    >>> bench.add_plot(name="layers", plot=ApproximationRatioVsParameterPlot(parameter="reps"))

    See Also
    --------
    RuntimeVsParameterPlot : What the same sweep costs in runtime.
    """

    figure: Figure = Figure(
        filename="approximation_ratio_vs_parameter",
        title="Approximation Ratio over the Parameter Sweep (1.0 = optimal)",
    )

    y: MetricDimension = MetricDimension(
        "approximation_ratio",
        "Approximation Ratio",
        reference=1.0,
        reference_label="Optimal (1.0)",
    )

    hline_label: str | None = "Optimal (1.0)"
    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(  # noqa: PLR0913
            self,
            *,
            style: PlotStyle | None = None,
            figure: Figure = Figure(
                filename="approximation_ratio_vs_parameter",
                title="Approximation Ratio over the Parameter Sweep (1.0 = optimal)",
            ),
            parameter: str = "reps",
            y: MetricDimension = MetricDimension(
                "approximation_ratio", "Approximation Ratio", reference=1.0, reference_label="Optimal (1.0)"
            ),
            xlabel: str = "",
            hue: str | None = "model",
            marker: str = "o",
            aggregation: Aggregation = Aggregation.MEAN,
            errorbars: ErrorBars | None = ErrorBars(),
            hline_label: str | None = "Optimal (1.0)",
        ) -> None: ...


@plot(Runtime)
class RuntimeVsParameterPlot(ParameterSweepPlot):
    """Runtime against a swept algorithm parameter, one line per model.

    The cost side of a sweep: read next to `ApproximationRatioVsParameterPlot` it shows
    what the extra layers, shots or iterations were paid with.

    Requires the ``Runtime`` metric.

    Attributes
    ----------
    parameter : str
        Attribute of the algorithm configuration that is swept, by default ``"reps"``.
    figure_filename : str
        Stem of the written figure files, by default ``"runtime_vs_parameter"``.

    Examples
    --------
    >>> bench.add_metric(name="runtime", metric=Runtime())
    >>> bench.add_plot(name="layer_cost", plot=RuntimeVsParameterPlot(parameter="reps"))
    """

    figure_filename: str = "runtime_vs_parameter"

    y: MetricDimension = MetricDimension("runtime_seconds", "Runtime (s)")

    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(  # noqa: PLR0913
            self,
            *,
            style: PlotStyle | None = None,
            figure: Figure = Figure(),
            parameter: str = "reps",
            y: MetricDimension = MetricDimension("runtime_seconds", "Runtime (s)"),
            xlabel: str = "",
            hue: str | None = "model",
            marker: str = "o",
            aggregation: Aggregation = Aggregation.MEAN,
            errorbars: ErrorBars | None = ErrorBars(),
            figure_filename: str = "runtime_vs_parameter",
        ) -> None: ...
