"""Metric sweeps over an algorithm parameter, e.g. the layer count of a QAOA."""

from __future__ import annotations

from typing import TYPE_CHECKING

from luna_bench.custom import plot
from luna_bench.metrics import ApproximationRatio, Runtime
from luna_bench.plots.dimensions import PERCENT, MetricDimension
from luna_bench.plots.generics.parameter_sweep_plot import ParameterSweepPlot
from luna_bench.plots.plot_style import Figure

if TYPE_CHECKING:
    from luna_bench.plots.dimensions import Dimension, ModelDimension, ParameterDimension
    from luna_bench.plots.plot_style import ErrorBars, Missing, PlotStyle, Theme
    from luna_bench.plots.utils import Aggregation


@plot(ApproximationRatio)
class ApproximationRatioVsParameterPlot(ParameterSweepPlot):
    """Approximation ratio against a swept algorithm parameter, one line per model.

    The plot for "does another QAOA layer buy anything": add one algorithm entry per
    value of the parameter, and the sweep shows how close to the optimum each of them
    got. ``100%`` - marked by the reference line - is the optimum.

    Requires the ``ApproximationRatio`` metric.

    Every display option is inherited and can be set when the plot is constructed, e.g.
    ``ApproximationRatioVsParameterPlot(x=ParameterDimension("layers"), grouping=None)``.
    `ParameterSweepPlot` documents the sweep itself; `SeabornPlot` the figure size and
    the output formats.

    Attributes
    ----------
    x : ParameterDimension
        The setting that is swept, by default ``ParameterDimension("reps")``.
    figure : Figure
        The figure, written to ``approximation_ratio_vs_parameter`` by default.

    Examples
    --------
    >>> for layers in (1, 2, 3, 4):
    ...     bench.add_algorithm(f"qaoa_p{layers}", QAOA(reps=layers))
    >>> bench.add_metric(name="approx_ratio", metric=ApproximationRatio())
    >>> plot = ApproximationRatioVsParameterPlot(x=ParameterDimension("reps", label="QAOA layers (p)"))
    >>> bench.add_plot(name="layers", plot=plot)

    See Also
    --------
    RuntimeVsParameterPlot : What the same sweep costs in runtime.
    """

    figure: Figure = Figure(
        filename="approximation_ratio_vs_parameter",
        title="Approximation Ratio over the Parameter Sweep (100% = optimal)",
    )

    y: MetricDimension = MetricDimension(
        "approximation_ratio",
        "Approximation Ratio [%]",
        scale=PERCENT,
        reference=PERCENT,
        reference_label="Optimal (100%)",
    )

    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(  # noqa: PLR0913
            self,
            *,
            figure: Figure = Figure(
                filename="approximation_ratio_vs_parameter",
                title="Approximation Ratio over the Parameter Sweep (100% = optimal)",
            ),
            missing: Missing = Missing(),
            x: ParameterDimension = ParameterDimension("reps"),
            y: MetricDimension = MetricDimension(
                "approximation_ratio",
                "Approximation Ratio [%]",
                scale=PERCENT,
                reference=PERCENT,
                reference_label="Optimal (100%)",
            ),
            grouping: Dimension | None = ModelDimension(),
            marker: str = "o",
            aggregation: Aggregation = Aggregation.MEAN,
            errorbars: ErrorBars | None = ErrorBars(),
            theme: Theme | None = Theme(),
            style: PlotStyle | None = None,
        ) -> None: ...


@plot(Runtime)
class RuntimeVsParameterPlot(ParameterSweepPlot):
    """Runtime against a swept algorithm parameter, one line per model.

    The cost side of a sweep: read next to `ApproximationRatioVsParameterPlot` it shows
    what the extra layers, shots or iterations were paid with.

    Requires the ``Runtime`` metric.

    Attributes
    ----------
    x : ParameterDimension
        The setting that is swept, by default ``ParameterDimension("reps")``.
    figure : Figure
        The figure, written to ``runtime_vs_parameter`` by default.

    Examples
    --------
    >>> bench.add_metric(name="runtime", metric=Runtime())
    >>> bench.add_plot(name="layer_cost", plot=RuntimeVsParameterPlot(x=ParameterDimension("reps")))
    """

    figure: Figure = Figure(filename="runtime_vs_parameter", title="Runtime over the Parameter Sweep")

    y: MetricDimension = MetricDimension("runtime_seconds", "Runtime (s)")

    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(  # noqa: PLR0913
            self,
            *,
            figure: Figure = Figure(filename="runtime_vs_parameter", title="Runtime over the Parameter Sweep"),
            missing: Missing = Missing(),
            x: ParameterDimension = ParameterDimension("reps"),
            y: MetricDimension = MetricDimension("runtime_seconds", "Runtime (s)"),
            grouping: Dimension | None = ModelDimension(),
            marker: str = "o",
            aggregation: Aggregation = Aggregation.MEAN,
            errorbars: ErrorBars | None = ErrorBars(),
            theme: Theme | None = Theme(),
            style: PlotStyle | None = None,
        ) -> None: ...
