"""Bar chart showing the number of variables per model."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from luna_bench.custom import plot
from luna_bench.features import VarNumberFeature
from luna_bench.plots.dimensions import Dimension, MetricDimension, ModelDimension
from luna_bench.plots.generics.bar_plot import BarPlot
from luna_bench.plots.plot_style import Figure

if TYPE_CHECKING:
    from luna_bench.custom import BenchmarkResultContainer
    from luna_bench.plots.dimensions import Dimension
    from luna_bench.plots.plot_style import Annotation, ErrorBars, Missing, PlotStyle, Theme
    from luna_bench.plots.utils import Aggregation


@plot(VarNumberFeature)
class VarNumberBarChartPlot(BarPlot):
    """Bar chart showing the number of variables per model.

    Every display option is inherited and can be set when the plot is constructed,
    e.g. ``VarNumberBarChartPlot(annotate=False, file_formats=("pgf", "png"))``.
    `BarPlot` documents the colours, error bars, value annotations and grouping by a
    feature; `SeabornPlot` the figure size and the output formats.

    Attributes
    ----------
    figure_filename : str
        Stem of the written figure files, by default ``"var_number_bar_chart"``.

    Examples
    --------
    >>> bench.add_feature(name="var_count", feature=VarNumberFeature())
    >>> bench.add_plot(name="var_number", plot=VarNumberBarChartPlot())
    """

    figure: Figure = Figure(
        filename="var_number_bar_chart",
        title="Variables per Model",
    )

    x: Dimension = ModelDimension()

    y: MetricDimension = MetricDimension("var_number", "Number of Variables")

    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(  # noqa: PLR0913
            self,
            *,
            figure: Figure = Figure(filename="var_number_bar_chart", title="Variables per Model"),
            missing: Missing = Missing(),
            x: Dimension = ModelDimension(),
            y: MetricDimension = MetricDimension("var_number", "Number of Variables"),
            aggregation: Aggregation = Aggregation.MEAN,
            errorbars: ErrorBars | None = ErrorBars(),
            annotation: Annotation | None = None,
            grouping: Dimension | None = None,
            theme: Theme | None = Theme(),
            style: PlotStyle | None = None,
        ) -> None: ...

    def run(self, benchmark_results: BenchmarkResultContainer, save_dir: str | None = None) -> None:
        """Generate plot output from benchmark results.

        Parameters
        ----------
        benchmark_results : BenchmarkResultContainer
            Aggregated benchmark data consumed by the plot implementation.
        """
        rows: list[dict[str, Any]] = [
            {
                "model": model_name,
                "var_number": benchmark_results.features[model_name].first(VarNumberFeature).var_number,
            }
            for model_name, feature_results in benchmark_results.features.items()
        ]

        self.draw(benchmark_results=benchmark_results, rows=rows, save_dir=save_dir)
