"""Expectation value metric for measuring the average solution quality."""

from typing import TYPE_CHECKING, ClassVar

from luna_model import Solution, ValueSource
from pydantic import Field

from luna_bench.custom import BaseMetric, FeatureResultContainer, MetricDirection, MetricResult, metric


class ExpectationValueResult(MetricResult):
    """Result container for the ExpectationValue metric.

    Attributes
    ----------
    expectation_value : float
        The expectation value of the solution, i.e. the count-weighted mean
        sample value over all samples.
    """

    expectation_value: float = Field(description="The expectation value of the solution.")


@metric
class ExpectationValue(BaseMetric[ExpectationValueResult]):
    """Metric that captures the expectation value of a solution.

    The expectation value is the mean objective value over all samples of a
    solution, weighted by how often each sample was observed. Unlike metrics
    that only look at the best sample, it reflects the quality of the whole
    sample distribution, which makes it useful for comparing the average
    performance of probabilistic solvers.

    Attributes
    ----------
    value_source : ValueSource
        Which sample values to average: ``ValueSource.OBJ`` evaluates the model's
        objective function, ``ValueSource.RAW`` uses the raw values reported by the
        solver. Default is ``ValueSource.OBJ``.
    direction : ClassVar[MetricDirection]
        ``DEPENDS_ON_SENSE``: this averages objective values, so the better expectation
        value is the lower one when minimizing and the higher one when maximizing. It
        cannot be ranked across models of different senses.

    Examples
    --------
    >>> from luna_bench.metrics import ExpectationValue
    >>> metric = ExpectationValue()
    >>> result = metric.run(solution, feature_results)
    >>> print(f"Expectation value: {result.expectation_value}")

    Averaging the raw solver values instead of the objective values:

    >>> from luna_model import ValueSource
    >>> metric = ExpectationValue(value_source=ValueSource.RAW)
    """

    direction: ClassVar[MetricDirection] = MetricDirection.DEPENDS_ON_SENSE

    value_source: ValueSource = ValueSource.OBJ

    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(
            self,
            *,
            value_source: ValueSource = ValueSource.OBJ,
        ) -> None: ...

    def run(self, solution: Solution, feature_results: FeatureResultContainer) -> ExpectationValueResult:  # noqa: ARG002
        """Compute the expectation value of the given solution.

        Parameters
        ----------
        solution : Solution
            The solution object whose samples are averaged.
        feature_results : FeatureResultContainer
            Container with pre-computed feature results (not used by this metric).

        Returns
        -------
        ExpectationValueResult
            Contains the count-weighted mean of the configured value source over
            all samples of the solution.
        """
        expectation_value = solution.expectation_value(value_toggle=self.value_source)
        return ExpectationValueResult(expectation_value=float(expectation_value))
