"""Bundles of plot options, so a plot is configured by concern rather than by keyword.

A plot carries every option as a field of its own, which is what makes a single tweak a
single keyword - ``RuntimePlot(width=12)``. Configuring several at once that way
turns into a wall of keywords, and sharing a look between plots means repeating it, so
the options are also grouped into bundles by what they configure:

.. code-block:: python

    plot = RuntimePlot(
        figure=Figure(width=12, dpi=200, show=False),
        annotation=Annotation(fontsize=7, max_decimals=6),
        grouping=FeatureDimension(feature=UseCaseFeature, label="Use case"),
        title="Runtime per Solver",
    )

`PlotStyle` collects the bundles into one look to hand to every plot of a benchmark. A
bundle carries only the options it was given, so anything it does not mention stays at
the plot's default, and the more specific setting wins: a plain keyword over a bundle,
and a bundle over the ``style`` it came with.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, ClassVar, Literal

from pydantic import BaseModel, ConfigDict, field_validator

from luna_bench.plots.utils import AUTO_ERRORBAR, ErrorBar, LunaColours


class OptionBundle(BaseModel):
    """Base of a bundle of plot options, passed to a plot as one argument.

    Only the options a bundle was given are handed to the plot - configure what you need,
    the rest is left alone. Options a given plot does not have are ignored by it, so the
    same bundle can be handed to bar plots, scatter plots and sweeps alike.

    Attributes
    ----------
    option_names : ClassVar[dict[str, str]]
        Bundle field to plot option, for the fields whose names differ. A field that is
        not listed keeps its name.
    """

    model_config = ConfigDict(extra="forbid")

    option_names: ClassVar[dict[str, str]] = {}

    def given(self) -> dict[str, Any]:
        """Return the options this bundle was given, under its own field names.

        Returns
        -------
        dict[str, Any]
            Field to value, in field order, for the fields that were passed. What was
            not passed is left out, so merging a bundle over another overrides only what
            it mentions.
        """
        return {name: getattr(self, name) for name in type(self).model_fields if name in self.model_fields_set}

    @classmethod
    def flat_names(cls) -> dict[str, str]:
        """Return the flat option names this bundle replaced, mapped to its fields.

        The options used to be one flat keyword each - ``annotate_fontsize`` rather than
        ``annotation=Annotation(fontsize=...)`` - and a plot still accepts those, so a
        configuration written or stored before the bundles keeps working.

        Returns
        -------
        dict[str, str]
            Flat option name to bundle field.
        """
        flat = {option: field for field, option in cls.option_names.items()}
        flat.update({name: name for name in cls.model_fields if name not in cls.option_names})
        return flat


class Figure(OptionBundle):
    r"""The figure a plot is drawn on and the files it is written to.

    Every field is documented on `SeabornPlot` under the name it maps to, which is the
    same name - ``Figure(width=12)`` sets ``width``.

    Attributes
    ----------
    width : int
        Figure width in inches.
    height : int
        Figure height in inches.
    dpi : int
        Resolution of the figure and of the raster files written from it.
    show : bool
        Open the figure in a window after building it.
    file_formats : tuple[str, ...] | str
        Output formats written to the save directory, one file each. ``"pgf"`` writes a
        figure to ``\input{}`` into a LaTeX document and needs a TeX engine.
    pgf_texsystem : str
        TeX engine used for the ``"pgf"`` format.
    filename : str
        Stem of the written files. The extension comes from *file_formats*.
    title : str
        Title above the figure.
    color : str | None
        Single colour for ungrouped bars, by default the Aqarios blue. Ignored once a
        grouping splits them, where the Luna gradient encodes the group.
    seaborn_kwargs : dict[str, Any]
        Extra arguments passed straight to the seaborn call that draws the plot. They
        override what the plot computed, so ``palette`` or ``estimator`` can be replaced
        as well as extended.
    """

    option_names: ClassVar[dict[str, str]] = {"filename": "figure_filename"}

    width: int = 8
    height: int = 6
    dpi: int = 100
    show: bool = True
    file_formats: tuple[str, ...] = ("png",)
    pgf_texsystem: str = "pdflatex"
    filename: str = "figure"
    title: str = ""
    color: str | None = None
    seaborn_kwargs: dict[str, Any] = {}  # pydantic copies a mutable default per instance.

    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(  # noqa: PLR0913
            self,
            *,
            width: int = 8,
            height: int = 6,
            dpi: int = 100,
            show: bool = True,
            file_formats: tuple[str, ...] = ("png",),
            pgf_texsystem: str = "pdflatex",
            filename: str = "figure",
            title: str = "",
            color: str | None = None,
            seaborn_kwargs: dict[str, Any] = {},  # noqa: B006
        ) -> None: ...

    @field_validator("file_formats", mode="before")
    @classmethod
    def _accept_single_format(cls, value: Any) -> Any:  # noqa: ANN401
        """Allow a plain string, so ``file_formats="pgf"`` works as well as ``("pgf",)``."""
        return (value,) if isinstance(value, str) else value


class ErrorBars(OptionBundle):
    """The error bars drawn on top of the bars.

    Every field maps to the plot option of the same name with an ``errorbar`` prefix, and
    is documented on `BarPlot`.

    Attributes
    ----------
    spec : ErrorBar
        What the bar shows (``"sd"``, ``("ci", 95)``, ``None`` to draw none). By default
        derived from the aggregation.
    color : str
        Colour of the error bars.
    capsize : float
        Width of the caps that turn an error bar into a T, as a share of the bar width.
        ``0.0`` leaves a plain line.
    """

    option_names: ClassVar[dict[str, str]] = {
        "spec": "errorbar",
        "color": "errorbar_color",
        "capsize": "errorbar_capsize",
    }

    spec: ErrorBar = AUTO_ERRORBAR
    color: str = LunaColours.SKY
    capsize: float = 0.2
    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(
            self,
            *,
            spec: ErrorBar = AUTO_ERRORBAR,
            color: str = LunaColours.SKY,
            capsize: float = 0.2,
        ) -> None: ...


class Annotation(OptionBundle):
    """The values written above the bars.

    Passing no annotation at all is how a plot says it wants none - ``annotation=None``
    rather than a flag inside the bundle, the same way ``grouping=None`` leaves the bars
    ungrouped.

    Every field maps to the plot option of the same name with an ``annotate`` prefix, and
    is documented on `BarPlot` - `format` is ``annotate_format``, and so on.

    Attributes
    ----------
    format : str
        Format applied to an annotated value, e.g. ``"{:.1f}%"``.
    max_decimals : int | None
        Decimals an annotation may use before it switches to scientific notation.
    fontsize : float | str
        Font size in points, or a matplotlib size name.
    rotation : int
        Rotation of the annotations in degrees.
    headroom : float
        Share of the y range added above the bars so the annotations fit.
    """

    option_names: ClassVar[dict[str, str]] = {
        "format": "annotate_format",
        "max_decimals": "annotate_max_decimals",
        "fontsize": "annotate_fontsize",
        "rotation": "annotate_rotation",
        "headroom": "annotate_headroom",
    }

    format: str = "{:.3g}"
    max_decimals: int | None = None
    fontsize: float | str = "small"
    rotation: int = 0
    headroom: float = 0.3
    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(
            self,
            *,
            format: str = "{:.3g}",
            max_decimals: int | None = None,
            fontsize: float | str = "small",
            rotation: int = 0,
            headroom: float = 0.3,
        ) -> None: ...


class Missing(OptionBundle):
    """What becomes of the values a plot cannot draw.

    Every benchmark produces some: a time to solution is infinite for a run that never
    reached the optimum, a ratio is undefined where the metric failed. By default they are
    left out of the figure and the figure says so, because carrying on quietly changes what
    it means - leaving them out shows a mean over fewer models than the axis claims,
    drawing them somewhere puts a number there that no run produced. Saying which of them
    happened is what keeps the figure readable, and it is what this chooses:

    .. code-block:: python

        TimeToSolutionPlot(missing=Missing(policy="mark"))  # the default: out, and said so
        TimeToSolutionPlot(missing=Missing(policy="drop"))  # leave them out, quietly
        TimeToSolutionPlot(missing=Missing(policy="max"))  # just past the tallest bar
        TimeToSolutionPlot(missing=Missing(policy=0.0))  # at a value of your own
        TimeToSolutionPlot(missing=Missing(policy="raise"))  # no figure at all

    A fill is spelled the way pandas aggregates a column: a name it understands, applied
    to the values that *could* be drawn - ``"max"``, ``"min"``, ``"mean"``, ``"median"``
    - times :attr:`factor`. ``"max"`` with the default factor puts them a tenth above the
    tallest bar, which reads as "worse than everything in this figure" without claiming a
    number for it. A plain float fills with that value instead.

    How loudly the figure says what happened follows from the policy:

    ``"drop"`` says nothing. The values are gone from the averages, the category keeps its
    place on the axis, and the empty slot is the whole statement - for a figure that is
    about the algorithms that did report something.

    ``"mark"`` - the default - says it plainly: the categories that lost values are struck
    through over the full height of the axes and carry a red cross with the number behind
    it, so a solver that reported nothing is not mistaken for one whose bar is merely
    short. It is the default because it is the only policy that changes nothing about what
    the figure claims: the values are as absent as under ``"drop"``, and the figure carries
    what happened to them instead of leaving it to the log.

    ``"raise"`` refuses the figure. For a benchmark where a missing value means the run
    itself went wrong rather than the solver having nothing to report - and where a page of
    figures that quietly excludes it would be worse than no page.

    A fill is always marked, whatever else it does. A bar drawn at the fill looks exactly
    like a measured one, so the cross and its count are what keep it honest - the figure
    shows where the value would be without claiming a run produced it.

    How much a figure can say depends on what it draws. A bar has a slot of its own to put
    a cross under and a category to strike through; a point in a cloud or a step of a sweep
    has neither, so there the mark is the count in the legend - enough that a filled value
    is not read as a measured one.

    A warning names the categories in the log under every policy, including ``"drop"``.

    Attributes
    ----------
    policy : float | Literal["raise", "mark", "drop", "max", "min", "mean", "median"]
        What happens to a value that cannot be drawn: ``"mark"`` - the default - leaves it
        out and strikes the category through, ``"drop"`` leaves it out and leaves its slot
        empty, a pandas aggregate draws it relative to the values that survived, a float
        draws it there, and ``"raise"`` refuses the figure.
    factor : float
        Multiplier on an aggregate fill, so ``"max"`` lands past the bars rather than on
        them. Ignored by ``"raise"``, ``"drop"``, ``"mark"``, and a constant.
    mark : bool
        Draw what the policy would say on the figure - the crosses, their counts, the
        legend entry, and the band ``"mark"`` strikes the categories through with.
        ``False`` leaves the log to say it all. ``"drop"`` says nothing either way.
    """

    policy: float | Literal["raise", "mark", "drop", "max", "min", "mean", "median"] = "mark"
    factor: float = 1.1
    mark: bool = True

    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(
            self,
            *,
            policy: float | Literal["raise", "mark", "drop", "max", "min", "mean", "median"] = "mark",
            factor: float = 1.1,
            mark: bool = True,
        ) -> None: ...


class Theme(OptionBundle):
    """The seaborn theme a figure is drawn under, and the gridlines behind the marks.

    Every plot has one: seaborn's ``whitegrid`` with horizontal lines behind the bars, so
    a value can be read off the axis rather than guessed from the height of a bar. Passing
    a theme changes that look, and ``theme=None`` takes it away entirely - matplotlib's own
    white background and no grid, the same way ``annotation=None`` leaves the values off
    the bars.

    .. code-block:: python

        PlotStyle(theme=Theme(seaborn_style="ticks", context="talk", grid="both")).use()

        bench.add_plot("runtime", RuntimePlot())  # whitegrid, horizontal lines
        bench.add_plot("quality", ApproximationRatioPlot(theme=Theme(grid="both")))
        bench.add_plot("bare", FeasibilityRatioPlot(theme=None))  # no theme, no grid

    Attributes
    ----------
    seaborn_style : Literal["darkgrid", "whitegrid", "dark", "white", "ticks"]
        The seaborn style the figure is drawn under, passed on as ``style``. It sets the
        background and the axes, and brings gridlines of its own with the ``grid``
        variants - :attr:`grid` is applied on top of whatever it draws.
    context : Literal["paper", "notebook", "talk", "poster"]
        Scale of the labels, lines and markers, for the medium the figure ends up in.
    font_scale : float
        Multiplier on top of the *context*, for a figure whose labels are still too small.
    grid : Literal["x", "y", "both"] | None
        Axis the gridlines run off, by default the value axis of a bar chart. ``None``
        leaves the figure without any, including the ones a ``grid`` style would draw.
    grid_color : str | None
        Colour of the gridlines, by default the one the seaborn style uses.
    grid_linestyle : str
        Matplotlib line style of the gridlines, e.g. ``"-"``, ``"--"``, ``":"``.
    grid_linewidth : float
        Width of the gridlines in points.
    grid_alpha : float
        Opacity of the gridlines. They sit behind the marks either way, so this is about
        how loud they are, not about what they cover.
    rc : dict[str, Any]
        Matplotlib rc parameters applied on top of the theme, for what it does not cover.
    """

    seaborn_style: Literal["darkgrid", "whitegrid", "dark", "white", "ticks"] = "whitegrid"
    context: Literal["paper", "notebook", "talk", "poster"] = "notebook"
    font_scale: float = 1.0
    grid: Literal["x", "y", "both"] | None = "y"
    grid_color: str | None = None
    grid_linestyle: str = "-"
    grid_linewidth: float = 0.8
    grid_alpha: float = 0.5
    rc: dict[str, Any] = {}  # pydantic copies a mutable default per instance.

    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(  # noqa: PLR0913
            self,
            *,
            seaborn_style: Literal["darkgrid", "whitegrid", "dark", "white", "ticks"] = "whitegrid",
            context: Literal["paper", "notebook", "talk", "poster"] = "notebook",
            font_scale: float = 1.0,
            grid: Literal["x", "y", "both"] | None = "y",
            grid_color: str | None = None,
            grid_linestyle: str = "-",
            grid_linewidth: float = 0.8,
            grid_alpha: float = 0.5,
            rc: dict[str, Any] = {},  # noqa: B006
        ) -> None: ...


class PlotStyle(OptionBundle):
    """The look of a benchmark's figures, configured once and given to every plot.

    .. code-block:: python

        style = PlotStyle(
            figure=Figure(width=12, dpi=200, show=False),
            theme=Theme(seaborn_style="whitegrid", grid="y"),
        )

        bench.add_plot("runtime", RuntimePlot(style=style, title="Runtime"))
        bench.add_plot("feasible", FeasibilityRatioPlot(style=style))
        # One plot that differs: the bundle it is given wins over the shared style.
        bench.add_plot("quality", BestSolutionFoundRatioPlot(style=style, theme=None))

    Only the look every figure has is collected here. What a bar means - the aggregation
    behind it, the spread on top of it, the values written above it, what splits it into a
    group, and what becomes of a value that is not there - is a statement about one plot,
    not about a benchmark's figures, so it is made on the plot. So is what identifies a
    single figure: its title, labels, limits, reference lines and filename.

    Attributes
    ----------
    figure : Figure | None
        The figure and the files written from it.
    theme : Theme | None
        The seaborn theme the figures are drawn under, and their gridlines, or ``None``
        to leave them as matplotlib draws them.

    A benchmark that wants one look everywhere installs the style once instead of handing
    it to every plot:

    .. code-block:: python

        PlotStyle(figure=Figure(width=12, show=False)).use()

        bench.add_plot("runtime", RuntimePlot())  # picks the style up
        bench.add_plot("quality", BestSolutionFoundRatioPlot(width=8))  # and can still differ

    See Also
    --------
    Figure, Theme : The bundles it collects.
    """

    _default: ClassVar[PlotStyle | None] = None

    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(
            self,
            *,
            figure: Figure | None = None,
            theme: Theme | None = None,
        ) -> None: ...

    def use(self) -> _StyleContext:
        """Make this the style every plot built from now on starts from.

        The plots pick it up as they are constructed, so installing a style does not
        change the ones that already exist - what a plot holds is always what it was
        built with. A plot still wins over it, with a bundle or with a plain option.

        Returns
        -------
        _StyleContext
            A context manager that puts the previous default back, for a style that
            should only apply to one block. Discard it to install the style for good.
        """
        previous = PlotStyle._default
        PlotStyle._default = self
        return _StyleContext(previous)

    @classmethod
    def installed(cls) -> PlotStyle | None:
        """Return the style plots currently start from, if one was installed.

        Returns
        -------
        PlotStyle | None
            The installed style, or ``None``.
        """
        return cls._default

    @classmethod
    def clear(cls) -> None:
        """Forget the installed style, so plots go back to their own defaults."""
        cls._default = None

    figure: Figure | None = None
    theme: Theme | None = None


class _StyleContext:
    """Puts the previous default style back when the block that installed one ends."""

    def __init__(self, previous: PlotStyle | None) -> None:
        self._previous = previous

    def __enter__(self) -> None:
        """Enter the block; the style was installed when it was asked for."""

    def __exit__(self, *exception: object) -> None:
        """Leave the block, restoring the style that was installed before."""
        if self._previous is None:
            PlotStyle.clear()
        else:
            self._previous.use()
