"""Approximation ratio per solver bar chart."""

from __future__ import annotations

from typing import TYPE_CHECKING

from luna_bench.custom import plot
from luna_bench.metrics import ApproximationRatio
from luna_bench.plots.dimensions import MetricDimension
from luna_bench.plots.generics.metric_bar_plot import MetricBarPlot
from luna_bench.plots.plot_style import Figure

if TYPE_CHECKING:
    from luna_bench.plots.dimensions import AlgorithmDimension, Dimension
    from luna_bench.plots.plot_style import Annotation, ErrorBars, PlotStyle
    from luna_bench.plots.utils import Aggregation


@plot(ApproximationRatio)
class ApproximationRatioPlot(MetricBarPlot):
    """Bar chart of the approximation ratio per algorithm.

    The approximation ratio compares an algorithm's objective value against the known
    optimum, so ``1.0`` - marked by the reference line - means the optimum was reached.
    One bar per algorithm, aggregated over every model - the mean by default, see
    :attr:`aggregation` - with the spread across those models as the error bar.

    Requires the ``ApproximationRatio`` metric.

    Every display option is inherited and can be set when the plot is constructed,
    e.g. ``ApproximationRatioPlot(annotate=False, file_formats=("pgf", "png"))``.
    `BarPlot` documents the colours, error bars, value annotations and grouping by a
    feature; `SeabornPlot` the figure size and the output formats.

    Attributes
    ----------
    figure_filename : str
        Stem of the written figure files, by default ``"approximation_ratio"``.

    Examples
    --------
    >>> bench.add_metric(name="approx_ratio", metric=ApproximationRatio())
    >>> bench.add_plot(name="avg_approx", plot=ApproximationRatioPlot())

    See Also
    --------
    ApproximationRatioVsVarNumberPlot : The same ratio against model size.
    """

    figure: Figure = Figure(
        filename="approximation_ratio",
        title="Approximation Ratio per Solver (1.0 = optimal)",
    )

    y: MetricDimension = MetricDimension(
        "approximation_ratio",
        "Approximation Ratio",
        reference=1.0,
        reference_label="Optimal (1.0)",
    )

    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(  # noqa: PLR0913
            self,
            *,
            style: PlotStyle | None = None,
            figure: Figure = Figure(
                filename="approximation_ratio", title="Approximation Ratio per Solver (1.0 = optimal)"
            ),
            x: Dimension = AlgorithmDimension(),
            y: MetricDimension = MetricDimension(
                "approximation_ratio", "Approximation Ratio", reference=1.0, reference_label="Optimal (1.0)"
            ),
            aggregation: Aggregation = Aggregation.MEAN,
            errorbars: ErrorBars | None = ErrorBars(),
            annotation: Annotation | None = None,
            grouping: Dimension | None = None,
        ) -> None: ...
