"""Best solution found ratio per algorithm bar chart."""

from __future__ import annotations

from typing import TYPE_CHECKING

from luna_bench.custom import plot
from luna_bench.metrics import BestSolutionFoundRatio
from luna_bench.plots.dimensions import MetricDimension
from luna_bench.plots.generics.metric_bar_plot import MetricBarPlot
from luna_bench.plots.plot_style import Figure

if TYPE_CHECKING:
    from luna_bench.plots.dimensions import AlgorithmDimension, Dimension
    from luna_bench.plots.plot_style import Annotation, ErrorBars, PlotStyle
    from luna_bench.plots.utils import Aggregation


@plot(BestSolutionFoundRatio)
class BestSolutionFoundRatioPlot(MetricBarPlot):
    """Bar chart of the best-solution-found ratio per algorithm.

    The share of samples that reached the best solution, averaged over every model,
    with the spread across those models as the error bar. Higher is better.

    Requires the ``BestSolutionFoundRatio`` metric.

    Every display option is inherited and can be set when the plot is constructed,
    e.g. ``BestSolutionFoundRatioPlot(annotate=False, file_formats=("pgf", "png"))``.
    `BarPlot` documents the colours, error bars, value annotations and grouping by a
    feature; `SeabornPlot` the figure size and the output formats.

    Attributes
    ----------
    figure_filename : str
        Stem of the written figure files, by default ``"best_solution_found_ratio"``.

    Examples
    --------
    >>> bench.add_metric(name="bsf_ratio", metric=BestSolutionFoundRatio())
    >>> bench.add_plot(name="avg_bsfr", plot=BestSolutionFoundRatioPlot())
    """

    figure: Figure = Figure(
        filename="best_solution_found_ratio",
        title="Best Solution Found Ratio per Solver (1.0 = optimal)",
    )

    y: MetricDimension = MetricDimension(
        "best_solution_found",
        "Best Solution Found Ratio",
        reference=1.0,
        reference_label="Optimal (1.0)",
        baseline=0.0,
    )

    baseline: float | None = 0.0
    """Zero line the bars stand on.

    A wide error bar can reach below zero, which leaves the bars floating in the axes
    without it - and where zero is, is what tells a ratio of 1.2 from one of 0.2.
    """

    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(  # noqa: PLR0913
            self,
            *,
            style: PlotStyle | None = None,
            figure: Figure = Figure(
                filename="best_solution_found_ratio", title="Best Solution Found Ratio per Solver (1.0 = optimal)"
            ),
            x: Dimension = AlgorithmDimension(),
            y: MetricDimension = MetricDimension(
                "best_solution_found",
                "Best Solution Found Ratio",
                reference=1.0,
                reference_label="Optimal (1.0)",
                baseline=0.0,
            ),
            aggregation: Aggregation = Aggregation.MEAN,
            errorbars: ErrorBars | None = ErrorBars(),
            annotation: Annotation | None = None,
            grouping: Dimension | None = None,
            baseline: float | None = 0.0,
        ) -> None: ...
