"""Share of models for which an algorithm found at least one feasible solution."""

from __future__ import annotations

from typing import TYPE_CHECKING

from luna_bench.custom import plot
from luna_bench.metrics import FeasibilityRatio
from luna_bench.plots.dimensions import PERCENT, MetricDimension
from luna_bench.plots.generics.metric_bar_plot import MetricBarPlot
from luna_bench.plots.plot_style import Annotation, Figure

if TYPE_CHECKING:
    from luna_bench.custom.base_results.metric_result import MetricResult
    from luna_bench.plots.dimensions import AlgorithmDimension, Dimension
    from luna_bench.plots.plot_style import ErrorBars, Missing, PlotStyle, Theme
    from luna_bench.plots.utils import Aggregation


@plot(FeasibilityRatio)
class FeasibleSolutionFoundPlot(MetricBarPlot):
    """Bar chart showing the percentage of models solved feasibly per algorithm.

    A model counts as solved when at least one sample was feasible, i.e. when the
    ``FeasibilityRatio`` is greater than zero. Averaging that indicator over all
    models gives the share of the benchmark an algorithm could handle at all,
    independent of how many of its samples were feasible.

    Every display option is inherited and can be set when the plot is constructed,
    e.g. ``FeasibleSolutionFoundPlot(annotate=False, file_formats=("pgf", "png"))``.
    `BarPlot` documents the colours, error bars, value annotations and grouping by a
    feature; `SeabornPlot` the figure size and the output formats.

    Attributes
    ----------
    figure_filename : str
        Stem of the written figure files, by default ``"feasible_solution_found"``.
    annotation : Annotation
        The values written above the bars, in percent by default.

    Examples
    --------
    >>> bench.add_metric(name="feasibility", metric=FeasibilityRatio())
    >>> bench.add_plot(name="feasible_found", plot=FeasibleSolutionFoundPlot())
    """

    figure: Figure = Figure(
        filename="feasible_solution_found",
        title="Models with a Feasible Solution per Algorithm",
    )
    annotation: Annotation | None = Annotation()

    y: MetricDimension = MetricDimension(
        "feasibility_ratio",
        "Feasible solution found [% of models]",
        scale=PERCENT,
        limits=(0, PERCENT),
        reference=PERCENT,
        reference_label="Upper Limit (100%)",
    )

    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(  # noqa: PLR0913
            self,
            *,
            figure: Figure = Figure(
                filename="feasible_solution_found", title="Models with a Feasible Solution per Algorithm"
            ),
            missing: Missing = Missing(),
            x: Dimension = AlgorithmDimension(),
            y: MetricDimension = MetricDimension(
                "feasibility_ratio",
                "Feasible solution found [% of models]",
                scale=PERCENT,
                limits=(0, PERCENT),
                reference=PERCENT,
                reference_label="Upper Limit (100%)",
            ),
            aggregation: Aggregation = Aggregation.MEAN,
            errorbars: ErrorBars | None = ErrorBars(),
            annotation: Annotation | None = Annotation(),
            grouping: Dimension | None = None,
            theme: Theme | None = Theme(),
            style: PlotStyle | None = None,
        ) -> None: ...

    def value(self, metric_result: MetricResult) -> float:
        """Return 100 when the algorithm found a feasible sample for this model, 0 otherwise.

        Parameters
        ----------
        metric_result : MetricResult
            The feasibility ratio of one model and algorithm.

        Returns
        -------
        float
            The indicator, in percent, so the bars average into the share of the
            benchmark an algorithm could handle at all.
        """
        return PERCENT if super().value(metric_result) > 0 else 0.0
