"""Feasibility ratio per solver bar chart."""

from __future__ import annotations

from typing import TYPE_CHECKING

from luna_bench.custom import plot
from luna_bench.metrics import FeasibilityRatio
from luna_bench.plots.dimensions import PERCENT, MetricDimension
from luna_bench.plots.generics.metric_bar_plot import MetricBarPlot
from luna_bench.plots.plot_style import Figure

if TYPE_CHECKING:
    from luna_bench.plots.dimensions import AlgorithmDimension, Dimension
    from luna_bench.plots.plot_style import Annotation, ErrorBars, Missing, PlotStyle, Theme
    from luna_bench.plots.utils import Aggregation


@plot(FeasibilityRatio)
class FeasibilityRatioPlot(MetricBarPlot):
    """Bar chart of the share of feasible samples per algorithm.

    Counts how many of the samples an algorithm returned satisfy all constraints,
    averaged over every model, with the spread across those models as the error bar.
    ``1.0`` means every sample was feasible.

    Requires the ``FeasibilityRatio`` metric.

    Every display option is inherited and can be set when the plot is constructed,
    e.g. ``FeasibilityRatioPlot(annotate=False, file_formats=("pgf", "png"))``.
    `BarPlot` documents the colours, error bars, value annotations and grouping by a
    feature; `SeabornPlot` the figure size and the output formats.

    Attributes
    ----------
    figure_filename : str
        Stem of the written figure files, by default ``"feasibility_ratio"``.

    Examples
    --------
    >>> bench.add_metric(name="feasibility", metric=FeasibilityRatio())
    >>> bench.add_plot(name="avg_feasibility", plot=FeasibilityRatioPlot())

    See Also
    --------
    FeasibleSolutionFoundPlot : Whether *any* feasible sample was found, per model.
    """

    figure: Figure = Figure(
        filename="feasibility_ratio",
        title="Feasibility Ratio per Solver",
    )

    y: MetricDimension = MetricDimension(
        "feasibility_ratio",
        "Feasibility Ratio [%]",
        scale=PERCENT,
        limits=(0, PERCENT),
        reference=PERCENT,
        reference_label="Upper Limit (100%)",
    )

    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(  # noqa: PLR0913
            self,
            *,
            figure: Figure = Figure(filename="feasibility_ratio", title="Feasibility Ratio per Solver"),
            missing: Missing = Missing(),
            x: Dimension = AlgorithmDimension(),
            y: MetricDimension = MetricDimension(
                "feasibility_ratio",
                "Feasibility Ratio [%]",
                scale=PERCENT,
                limits=(0, PERCENT),
                reference=PERCENT,
                reference_label="Upper Limit (100%)",
            ),
            aggregation: Aggregation = Aggregation.MEAN,
            errorbars: ErrorBars | None = ErrorBars(),
            annotation: Annotation | None = None,
            grouping: Dimension | None = None,
            theme: Theme | None = Theme(),
            style: PlotStyle | None = None,
        ) -> None: ...
