"""Share of feasible samples per solver, pooled over all models."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from luna_bench.custom import plot
from luna_bench.metrics import FeasibleSamples
from luna_bench.plots.generics.bar_plot import BarPlot

if TYPE_CHECKING:
    from luna_bench.custom import BenchmarkResultContainer
    from luna_bench.custom.types import FeatureClass
    from luna_bench.plots.utils import LunaColours


@plot(FeasibleSamples)
class FeasibleSampleRatioPlot(BarPlot):
    """Bar chart of the feasible samples an algorithm produced over all its samples.

    The counts are pooled before dividing: every sample of every model enters the same
    sum, so an algorithm that returns a thousand samples on one model and ten on another
    is judged by its samples rather than by its models. That is the difference to
    `AverageFeasibilityRatioPlot`, which averages the per-model ratios and therefore
    weights both models equally. ``1.0`` - marked by the reference line - means every
    sample was feasible.

    Because each bar is a single pooled number there is no spread to show, so the bars
    carry no error bars.

    Requires the ``FeasibleSamples`` metric.

    Every display option is inherited and can be set when the plot is constructed,
    e.g. ``FeasibleSampleRatioPlot(annotate=False, file_formats=("pgf", "png"))``.
    `BarPlot` documents the colours, value annotations and grouping by a feature;
    `SeabornPlot` the figure size and the output formats.

    Attributes
    ----------
    figure_filename : str
        Stem of the written figure files, by default ``"feasible_sample_ratio"``.

    Examples
    --------
    >>> bench.add_metric(name="feasible_samples", metric=FeasibleSamples())
    >>> bench.add_plot(name="feasible_share", plot=FeasibleSampleRatioPlot())

    See Also
    --------
    AverageFeasibilityRatioPlot : The same share averaged per model instead of pooled.
    FeasibleSolutionFoundPlot : Whether *any* feasible sample was found, per model.
    """

    figure_filename: str = "feasible_sample_ratio"

    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(  # noqa: PLR0913
            self,
            *,
            width: int = 8,
            height: int = 6,
            dpi: int = 100,
            show: bool = True,
            file_formats: tuple[str, ...] = ("png",),
            pgf_texsystem: str = "pdflatex",
            figure_filename: str = "feasible_sample_ratio",
            color: str | None = None,
            errorbar_color: str = LunaColours.SKY,
            errorbar_capsize: float = 0.2,
            annotate: bool = True,
            annotate_format: str = "{:.3g}",
            annotate_rotation: int = 0,
            annotate_headroom: float = 0.3,
            group_by: FeatureClass | None = None,
            group_label: str | None = None,
            group_attribute: str = "value",
        ) -> None: ...

    def run(self, benchmark_results: BenchmarkResultContainer, save_dir: str | None = None) -> None:
        """Generate plot output from benchmark results.

        Parameters
        ----------
        benchmark_results : BenchmarkResultContainer
            Aggregated benchmark data consumed by the plot implementation.
        """
        rows: list[dict[str, Any]] = [
            {
                "algorithm": algorithm_name,
                "model": model_name,
                "num_feasible_samples": metric_result.num_feasible_samples,
                "num_samples": metric_result.num_samples,
            }
            for model_name, algorithm_name, metric_result in benchmark_results.get_all_metrics_of_type(FeasibleSamples)
        ]

        grouping = self.apply_grouping(benchmark_results, rows)

        self.create(
            save_dir=save_dir,
            rows=self._pool(rows, grouping.get("hue")),
            x="algorithm",
            y="feasible_sample_ratio",
            xlabel="Algorithm",
            ylabel="Feasible Samples / All Samples",
            title="Share of Feasible Samples per Solver (pooled over models)",
            ylim=(0, 1.15),
            errorbar=None,
            hline=1.0,
            hline_label="Upper Limit (1.0)",
            **grouping,
        )

    @staticmethod
    def _pool(rows: list[dict[str, Any]], group_key: str | None) -> list[dict[str, Any]]:
        """Sum the sample counts per algorithm and turn each pair of sums into a ratio.

        Parameters
        ----------
        rows : list[dict[str, Any]]
            One row per model and algorithm, carrying both sample counts.
        group_key : str | None
            Column the bars are split by, or ``None`` when they are ungrouped. Pooling
            happens within a group so a grouped plot keeps one bar per group.

        Returns
        -------
        list[dict[str, Any]]
            One row per bar, in the order the algorithms first appear.
        """
        totals: dict[tuple[str, str | None], list[int]] = {}
        for row in rows:
            key = (row["algorithm"], row[group_key] if group_key is not None else None)
            sums = totals.setdefault(key, [0, 0])
            sums[0] += row["num_feasible_samples"]
            sums[1] += row["num_samples"]

        pooled: list[dict[str, Any]] = []
        for (algorithm, group), (num_feasible, num_samples) in totals.items():
            pooled_row: dict[str, Any] = {
                "algorithm": algorithm,
                "feasible_sample_ratio": num_feasible / num_samples if num_samples else 0.0,
            }
            if group_key is not None:
                pooled_row[group_key] = group
            pooled.append(pooled_row)
        return pooled
