"""Share of feasible samples per solver, pooled over all models."""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

from luna_bench.custom import plot
from luna_bench.metrics import FeasibleSamples
from luna_bench.plots.dimensions import MetricDimension
from luna_bench.plots.generics.metric_bar_plot import MetricBarPlot
from luna_bench.plots.plot_style import ErrorBars, Figure

if TYPE_CHECKING:
    from luna_bench.custom import BenchmarkResultContainer
    from luna_bench.plots.dimensions import AlgorithmDimension, Dimension
    from luna_bench.plots.plot_style import Annotation, PlotStyle
    from luna_bench.plots.utils import Aggregation


@plot(FeasibleSamples)
class FeasibleSampleRatioPlot(MetricBarPlot):
    """Bar chart of the feasible samples an algorithm produced over all its samples.

    The counts are pooled before dividing: every sample of every model enters the same
    sum, so an algorithm that returns a thousand samples on one model and ten on another
    is judged by its samples rather than by its models. That is the difference to
    `FeasibilityRatioPlot`, which averages the per-model ratios and therefore
    weights both models equally. ``1.0`` - marked by the reference line - means every
    sample was feasible.

    Because each bar is a single pooled number there is no spread to show, so the bars
    carry no error bars.

    Requires the ``FeasibleSamples`` metric.

    Every display option is inherited and can be set when the plot is constructed,
    e.g. ``FeasibleSampleRatioPlot(annotate=False, file_formats=("pgf", "png"))``.
    `BarPlot` documents the colours, value annotations and grouping by a feature;
    `SeabornPlot` the figure size and the output formats.

    Attributes
    ----------
    figure_filename : str
        Stem of the written figure files, by default ``"feasible_sample_ratio"``.

    Examples
    --------
    >>> bench.add_metric(name="feasible_samples", metric=FeasibleSamples())
    >>> bench.add_plot(name="feasible_share", plot=FeasibleSampleRatioPlot())

    See Also
    --------
    FeasibilityRatioPlot : The same share averaged per model instead of pooled.
    FeasibleSolutionFoundPlot : Whether *any* feasible sample was found, per model.
    """

    figure: Figure = Figure(
        filename="feasible_sample_ratio",
        title="Share of Feasible Samples per Solver (pooled over models)",
    )

    y: MetricDimension = MetricDimension(
        "feasible_sample_ratio",
        "Feasible Samples / All Samples",
        limits=(0, 1.15),
        reference=1.0,
        reference_label="Upper Limit (1.0)",
    )

    errorbars: ErrorBars | None = None
    """No error bar: each bar is a single pooled number, so there is no spread to show."""

    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(  # noqa: PLR0913
            self,
            *,
            style: PlotStyle | None = None,
            figure: Figure = Figure(
                filename="feasible_sample_ratio", title="Share of Feasible Samples per Solver (pooled over models)"
            ),
            x: Dimension = AlgorithmDimension(),
            y: MetricDimension = MetricDimension(
                "feasible_sample_ratio",
                "Feasible Samples / All Samples",
                limits=(0, 1.15),
                reference=1.0,
                reference_label="Upper Limit (1.0)",
            ),
            aggregation: Aggregation = Aggregation.MEAN,
            errorbars: ErrorBars | None = None,
            annotation: Annotation | None = None,
            grouping: Dimension | None = None,
        ) -> None: ...

    def rows(self, benchmark_results: BenchmarkResultContainer) -> list[dict[str, Any]]:
        """Return one row per model and algorithm, carrying both sample counts.

        Parameters
        ----------
        benchmark_results : BenchmarkResultContainer
            Aggregated benchmark data.

        Returns
        -------
        list[dict[str, Any]]
            Rows to be pooled into one bar per algorithm by :meth:`transform_rows`.
        """
        return [
            {
                "algorithm": algorithm_name,
                "model": model_name,
                "num_feasible_samples": metric_result.num_feasible_samples,
                "num_samples": metric_result.num_samples,
            }
            for model_name, algorithm_name, metric_result in benchmark_results.get_all_metrics_of_type(FeasibleSamples)
        ]

    def transform_rows(self, rows: list[dict[str, Any]], x: str | None, group: str | None) -> list[dict[str, Any]]:
        """Pool the per-model counts into one ratio per bar.

        Parameters
        ----------
        rows : list[dict[str, Any]]
            One row per model and algorithm, carrying both sample counts.
        x : str | None
            Column the bars are drawn per.
        group : str | None
            Column the bars are split by, or ``None`` when they are ungrouped.

        Returns
        -------
        list[dict[str, Any]]
            One row per bar, in the order the bars first appear.
        """
        return self._pool(rows, [column for column in (x, group) if column is not None])

    @staticmethod
    def _pool(rows: list[dict[str, Any]], columns: list[str]) -> list[dict[str, Any]]:
        """Sum the sample counts per bar and turn each pair of sums into a ratio.

        Parameters
        ----------
        rows : list[dict[str, Any]]
            One row per model and algorithm, carrying both sample counts.
        columns : list[str]
            What tells one bar from another - the x-axis, and the grouping if there is
            one. Everything else is pooled over, which is the point of this plot: the
            samples of every model it pools enter the same sum.

        Returns
        -------
        list[dict[str, Any]]
            One row per bar, in the order the bars first appear.
        """
        totals: dict[tuple[Any, ...], list[int]] = {}
        for row in rows:
            key = tuple(row.get(column) for column in columns)
            sums = totals.setdefault(key, [0, 0])
            sums[0] += row["num_feasible_samples"]
            sums[1] += row["num_samples"]

        return [
            dict(zip(columns, key, strict=True))
            | {"feasible_sample_ratio": num_feasible / num_samples if num_samples else 0.0}
            for key, (num_feasible, num_samples) in totals.items()
        ]
