"""Fraction of the overall best solution per solver bar chart."""

from __future__ import annotations

from typing import TYPE_CHECKING

from luna_bench.custom import plot
from luna_bench.metrics.fraction_of_overall_best_solution import FractionOfOverallBestSolution
from luna_bench.plots.dimensions import MetricDimension
from luna_bench.plots.generics.metric_bar_plot import MetricBarPlot
from luna_bench.plots.plot_style import Figure

if TYPE_CHECKING:
    from luna_bench.plots.dimensions import AlgorithmDimension, Dimension
    from luna_bench.plots.plot_style import Annotation, ErrorBars, PlotStyle
    from luna_bench.plots.utils import Aggregation


@plot(FractionOfOverallBestSolution)
class FractionOfOverallBestSolutionPlot(MetricBarPlot):
    """Bar chart of the fraction of the overall best solution per algorithm.

    Each algorithm's objective value is measured against the best value *any*
    algorithm in the benchmark reached for that model, so ``1.0`` - marked by the
    reference line - means it was the best of the field. Useful when no optimum is
    known. Aggregated over every model - the mean by default - with the spread as the error bar.

    Requires the ``FractionOfOverallBestSolution`` metric.

    Every display option is inherited and can be set when the plot is constructed,
    e.g. ``FractionOfOverallBestSolutionPlot(annotate=False, file_formats=("pgf", "png"))``.
    `BarPlot` documents the colours, error bars, value annotations and grouping by a
    feature; `SeabornPlot` the figure size and the output formats.

    Attributes
    ----------
    figure_filename : str
        Stem of the written figure files, by default ``"fraction_of_overall_best_solution"``.

    Examples
    --------
    >>> bench.add_metric(name="best_found", metric=FractionOfOverallBestSolution())
    >>> bench.add_plot(name="avg_best", plot=FractionOfOverallBestSolutionPlot())
    """

    figure: Figure = Figure(
        filename="fraction_of_overall_best_solution",
        title="Best Solution Found per Solver (1.0 = optimal)",
    )

    y: MetricDimension = MetricDimension(
        "fraction_of_overall_best_solution",
        "Best Solution Found",
        reference=1.0,
        reference_label="Optimal (1.0)",
        baseline=0.0,
    )

    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(  # noqa: PLR0913
            self,
            *,
            style: PlotStyle | None = None,
            figure: Figure = Figure(
                filename="fraction_of_overall_best_solution", title="Best Solution Found per Solver (1.0 = optimal)"
            ),
            x: Dimension = AlgorithmDimension(),
            y: MetricDimension = MetricDimension(
                "fraction_of_overall_best_solution",
                "Best Solution Found",
                reference=1.0,
                reference_label="Optimal (1.0)",
                baseline=0.0,
            ),
            aggregation: Aggregation = Aggregation.MEAN,
            errorbars: ErrorBars | None = ErrorBars(),
            annotation: Annotation | None = None,
            grouping: Dimension | None = None,
        ) -> None: ...
