"""Runtime per solver bar chart."""

from __future__ import annotations

from typing import TYPE_CHECKING

from luna_bench.custom import plot
from luna_bench.metrics.runtime import Runtime
from luna_bench.plots.dimensions import MetricDimension
from luna_bench.plots.generics.metric_bar_plot import MetricBarPlot
from luna_bench.plots.plot_style import Figure

if TYPE_CHECKING:
    from luna_bench.plots.dimensions import AlgorithmDimension, Dimension
    from luna_bench.plots.plot_style import Annotation, ErrorBars, Missing, PlotStyle, Theme
    from luna_bench.plots.utils import Aggregation


@plot(Runtime)
class RuntimePlot(MetricBarPlot):
    """Bar chart of the wall-clock runtime each algorithm needed.

    One bar per algorithm, aggregated over every model in the benchmark - the mean by
    default, see :attr:`aggregation` - with the spread across those models as the error bar. Lower is better.

    Requires the ``Runtime`` metric.

    Every display option is inherited and can be set when the plot is constructed,
    e.g. ``RuntimePlot(annotate=False, file_formats=("pgf", "png"))``.
    `BarPlot` documents the colours, error bars, value annotations and grouping by a
    feature; `SeabornPlot` the figure size and the output formats.

    Attributes
    ----------
    figure_filename : str
        Stem of the written figure files, by default ``"runtime"``.

    Examples
    --------
    >>> bench.add_metric(name="runtime", metric=Runtime())
    >>> bench.add_plot(name="avg_runtime", plot=RuntimePlot())

    See Also
    --------
    RuntimePerModelPlot : The same numbers broken down per model.
    """

    figure: Figure = Figure(
        filename="runtime",
        title="Runtime per Solver",
    )

    y: MetricDimension = MetricDimension("runtime_seconds", "Runtime (s)", baseline=0.0)
    """Runtime in seconds, standing on a solid line at zero.

    A runtime cannot go below zero, and a wide error bar reaching under the bars leaves
    them floating in the axes without something to stand on. The line is where the bars
    start, which is what tells a solver that took twice as long from one that took half.
    """

    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(  # noqa: PLR0913
            self,
            *,
            figure: Figure = Figure(filename="runtime", title="Runtime per Solver"),
            missing: Missing = Missing(),
            x: Dimension = AlgorithmDimension(),
            y: MetricDimension = MetricDimension("runtime_seconds", "Runtime (s)", baseline=0.0),
            aggregation: Aggregation = Aggregation.MEAN,
            errorbars: ErrorBars | None = ErrorBars(),
            annotation: Annotation | None = None,
            grouping: Dimension | None = None,
            theme: Theme | None = Theme(),
            style: PlotStyle | None = None,
        ) -> None: ...
