"""Runtime per model grouped by algorithm."""

from __future__ import annotations

from typing import TYPE_CHECKING

from luna_bench.custom import plot
from luna_bench.metrics import Runtime
from luna_bench.plots.dimensions import AlgorithmDimension, Dimension, MetricDimension, ModelDimension
from luna_bench.plots.generics.metric_bar_plot import MetricBarPlot
from luna_bench.plots.plot_style import Figure

if TYPE_CHECKING:
    from luna_bench.plots.plot_style import Annotation, ErrorBars, Missing, PlotStyle, Theme
    from luna_bench.plots.utils import Aggregation


@plot(Runtime)
class RuntimePerModelPlot(MetricBarPlot):
    """Bar chart of runtime per model, with one bar per algorithm inside each model.

    Keeps the models apart instead of averaging over them, which shows where a
    single hard instance drives an algorithm's average runtime up.

    Requires the ``Runtime`` metric.

    Every display option is inherited and can be set when the plot is constructed,
    e.g. ``RuntimePerModelPlot(annotate=False, file_formats=("pgf", "png"))``.
    `BarPlot` documents the colours, error bars and value annotations; `SeabornPlot` the
    figure size and the output formats. ``group_by`` does not apply here - this plot
    already uses the hue channel for the algorithm.

    Attributes
    ----------
    figure_filename : str
        Stem of the written figure files, by default ``"runtime_per_model"``.

    Examples
    --------
    >>> bench.add_metric(name="runtime", metric=Runtime())
    >>> bench.add_plot(name="runtime_per_model", plot=RuntimePerModelPlot())

    See Also
    --------
    RuntimePlot : The same numbers averaged over all models.
    """

    figure: Figure = Figure(
        filename="runtime_per_model",
        title="Runtime per Model by Algorithm",
    )

    x: Dimension = ModelDimension()

    y: MetricDimension = MetricDimension("runtime_seconds", "Runtime (s)", baseline=0.0)
    """Runtime in seconds, standing on a solid line at zero, as on `RuntimePlot`."""

    grouping: Dimension | None = AlgorithmDimension()

    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(  # noqa: PLR0913
            self,
            *,
            figure: Figure = Figure(filename="runtime_per_model", title="Runtime per Model by Algorithm"),
            missing: Missing = Missing(),
            x: Dimension = ModelDimension(),
            y: MetricDimension = MetricDimension("runtime_seconds", "Runtime (s)", baseline=0.0),
            aggregation: Aggregation = Aggregation.MEAN,
            errorbars: ErrorBars | None = ErrorBars(),
            annotation: Annotation | None = None,
            grouping: Dimension | None = AlgorithmDimension(),
            theme: Theme | None = Theme(),
            style: PlotStyle | None = None,
        ) -> None: ...
