"""Time to solution per solver bar chart."""

from __future__ import annotations

from typing import TYPE_CHECKING

from luna_bench.custom import plot
from luna_bench.metrics import TimeToSolution
from luna_bench.plots.dimensions import MetricDimension
from luna_bench.plots.generics.metric_bar_plot import MetricBarPlot
from luna_bench.plots.plot_style import Figure

if TYPE_CHECKING:
    from luna_bench.plots.dimensions import AlgorithmDimension, Dimension
    from luna_bench.plots.plot_style import Annotation, ErrorBars, PlotStyle
    from luna_bench.plots.utils import Aggregation


@plot(TimeToSolution)
class TimeToSolutionPlot(MetricBarPlot):
    """Bar chart of the time to solution (TTS) per algorithm.

    TTS is the runtime an algorithm needs to reach its target solution with a given
    confidence, so it weighs speed against success rate. One bar per algorithm,
    averaged over every model, with the spread across those models as the error bar.
    Lower is better.

    Requires the ``TimeToSolution`` metric.

    Every display option is inherited and can be set when the plot is constructed,
    e.g. ``TimeToSolutionPlot(annotate=False, file_formats=("pgf", "png"))``.
    `BarPlot` documents the colours, error bars, value annotations and grouping by a
    feature; `SeabornPlot` the figure size and the output formats.

    Attributes
    ----------
    figure_filename : str
        Stem of the written figure files, by default ``"time_to_solution"``.

    Examples
    --------
    >>> bench.add_metric(name="time_to_solution", metric=TimeToSolution())
    >>> bench.add_plot(name="avg_tts", plot=TimeToSolutionPlot())
    """

    figure: Figure = Figure(
        filename="time_to_solution",
        title="Time to Solution per Algorithm (lower is better)",
    )

    y: MetricDimension = MetricDimension("time_to_solution", "Time to Solution (TTS)")

    if TYPE_CHECKING:
        # --- generated by scripts/type_hints.py, do not edit by hand ---
        # Mirrors the pydantic fields so IDEs show every option on the constructor.
        # Never executed: pydantic builds the real ``__init__``.
        def __init__(  # noqa: PLR0913
            self,
            *,
            style: PlotStyle | None = None,
            figure: Figure = Figure(
                filename="time_to_solution", title="Time to Solution per Algorithm (lower is better)"
            ),
            x: Dimension = AlgorithmDimension(),
            y: MetricDimension = MetricDimension("time_to_solution", "Time to Solution (TTS)"),
            aggregation: Aggregation = Aggregation.MEAN,
            errorbars: ErrorBars | None = ErrorBars(),
            annotation: Annotation | None = None,
            grouping: Dimension | None = None,
        ) -> None: ...
