"""Generate the explicit ``__init__`` signatures of the built-in components.

Pydantic builds a model's ``__init__`` at runtime, so an IDE has no source signature to
show: hovering ``RuntimePlot(`` or ``OptSolFeature(`` yields a bare class header
and the available options stay invisible until the user opens the base classes. To fix
that, every built-in plot, metric and feature that has fields carries a hand-visible
``__init__`` under ``if TYPE_CHECKING`` - never executed, so pydantic still builds and
validates the real constructor, but IDEs and type checkers read the parameters straight
off it.

Keeping those copies correct by hand is not realistic, so this module derives them from
``model_fields`` and writes them into the component modules:

    uv run python scripts/type_hints.py          # rewrite the signatures
    uv run python scripts/type_hints.py --check  # fail if any is out of date

``tests/unit/components/test_type_hints.py`` runs the same check, so a field that is
added, retyped, or given a new default cannot silently drift away from its signature.
"""

from __future__ import annotations

import argparse
import ast
import builtins
import inspect
import re
import subprocess
from pathlib import Path
from typing import TYPE_CHECKING, NamedTuple

if TYPE_CHECKING:
    from collections.abc import Iterator

    from pydantic import BaseModel
    from pydantic.fields import FieldInfo

REPO_ROOT = Path(__file__).resolve().parent.parent

#: Parameters that are about the look every figure of a benchmark shares rather than about
#: this plot, and how far back they are sorted. They are usually set once - installed as a
#: `PlotStyle`, or handed to every plot - so they belong at the end of a signature, behind
#: what makes this plot the plot it is.
SHARED_LOOK = {"theme": 1, "style": 2}

#: Packages whose public components are constructed by users, and so want a signature.
COMPONENT_PACKAGES = ("luna_bench.plots", "luna_bench.metrics", "luna_bench.features")

#: Opens the generated block. The whole ``if TYPE_CHECKING`` body is owned by this
#: script and replaced wholesale on every run.
MARKER = "# --- generated by scripts/type_hints.py, do not edit by hand ---"

#: Ruff's limit before a function needs to justify its parameter count.
_MAX_ARGS_WITHOUT_NOQA = 5

#: Defaults ruff reports as mutable, which pydantic copies per instance.
_COPIED_DEFAULTS = ("{}", "[]", "set()")


class Parameter(NamedTuple):
    """One constructor parameter, rendered exactly as its field is declared."""

    name: str
    annotation: str
    default: str | None


def component_classes() -> list[type[BaseModel]]:
    """Return every public component that has fields to show on its constructor.

    That is the plots, metrics and features themselves, whose metaclass hides the
    constructor pydantic builds, and the option bundles a plot is configured with. Their
    results are left out: they are plain pydantic models, which IDEs already understand
    and which the components build rather than the user. A class that writes its own
    ``__init__`` - a dimension, which takes its subject positionally - already has a
    signature to show, and one without fields has nothing to.
    """
    import importlib  # noqa: PLC0415

    from luna_bench.custom.base_components.registerable_component import RegisterableComponent  # noqa: PLC0415
    from luna_bench.plots.plot_style import OptionBundle  # noqa: PLC0415

    wanted = (RegisterableComponent, OptionBundle)

    classes: list[type[BaseModel]] = []
    for package in COMPONENT_PACKAGES:
        module = importlib.import_module(package)
        for name in module.__all__:
            candidate = getattr(module, name)
            if (
                isinstance(candidate, type)
                and issubclass(candidate, wanted)
                and candidate.model_fields
                and not _declares_runtime_init(candidate)
            ):
                classes.append(candidate)

    return classes


def _declares_runtime_init(cls: type) -> bool:
    """Return whether *cls* writes an ``__init__`` of its own outside the block."""
    tree = _module_tree(cls)
    if tree is None:  # pragma: no cover - defensive
        return False

    class_def = _class_def(tree, cls.__name__)
    return any(isinstance(node, ast.FunctionDef) and node.name == "__init__" for node in class_def.body)


def _module_tree(cls: type) -> ast.Module | None:
    """Return the parsed module that defines *cls*, or ``None`` without source."""
    try:
        return ast.parse(Path(inspect.getfile(cls)).read_text())
    except (OSError, TypeError, SyntaxError):  # builtins and classes without source on disk
        return None


def _declarations(cls: type) -> Iterator[tuple[str, Parameter]]:
    """Yield the annotated assignments in the body of *cls* as they are written."""
    tree = _module_tree(cls)
    if tree is None:
        return

    try:
        class_def = _class_def(tree, cls.__name__)
    except LookupError:  # pragma: no cover - defensive
        return

    for node in class_def.body:
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            name = node.target.id
            default = ast.unparse(node.value) if node.value is not None else None
            yield name, Parameter(name, ast.unparse(node.annotation), default)


def signature(cls: type[BaseModel]) -> list[Parameter]:
    """Return the constructor parameters of *cls*, what it is about first.

    The names come from ``model_fields``, which is what pydantic itself builds the
    constructor from, in the order it declares them - except for the ones in
    `SHARED_LOOK`, which go last. Those say how a whole benchmark's figures look and are
    normally set once, away from the plot; what this plot measures and how it reads is
    what someone opening the signature came for.

    The annotation and default are taken from the source of the class that declares the
    field, so a symbolic default such as ``LunaColours.SKY`` stays symbolic instead of
    being flattened into its value - except where the source form does not apply to
    *cls*, which `_resolved` fills in from the field itself.
    """
    declared: dict[str, Parameter] = {}
    type_params: set[str] = set()
    for base in reversed(cls.__mro__):
        declared.update(dict(_declarations(base)))
        type_params.update(param.__name__ for param in getattr(base, "__type_params__", ()))

    fields = [_resolved(cls, declared[name], type_params) for name in cls.model_fields if name in declared]
    parameters = fields + _option_bundles(cls)

    return sorted(parameters, key=lambda parameter: SHARED_LOOK.get(parameter.name, 0))


def _resolved(cls: type[BaseModel], parameter: Parameter, type_params: set[str]) -> Parameter:
    """Return *parameter* with anything the declaring class left open filled in for *cls*.

    A field inherited from a generic base is written in terms of that base's type
    parameters - ``mapping: dict[int, TValue]`` - which say nothing on a subclass that
    binds them and do not even exist as names in the subclass' module. A field given a
    ``Field(...)`` default is written as that call, which is not what a caller passing the
    argument sees. Both are read back off the built field instead, where pydantic has
    already resolved the parametrization.
    """
    field = cls.model_fields[parameter.name]

    annotation = parameter.annotation
    if _names_in(annotation) & type_params:
        annotation = _unqualify(str(field.annotation))

    default = parameter.default
    if default is not None and default.startswith("Field("):
        default = _caller_default(field)

    return Parameter(parameter.name, annotation, default)


def _names_in(source: str) -> set[str]:
    """Return the names an annotation refers to."""
    return {node.id for node in ast.walk(ast.parse(source, mode="eval")) if isinstance(node, ast.Name)}


def _unqualify(annotation: str) -> str:
    """Strip module paths from a runtime annotation, leaving the names as source writes them."""
    return re.sub(r"[\w.]*\.(\w+)", r"\1", annotation)


def _caller_default(field: FieldInfo) -> str | None:
    """Return the default a caller of the constructor sees, as source.

    A ``default_factory`` has no source form of its own, so it is rendered as the literal
    the factory builds - which is what `_render_parameter` already knows to exempt from
    the mutable-default rule.
    """
    if field.default_factory is not None:
        literals: dict[object, str] = {dict: "{}", list: "[]", set: "set()"}
        return literals.get(field.default_factory, "...")
    if field.is_required():
        return None
    return repr(field.default)


def _option_bundles(cls: type[BaseModel]) -> list[Parameter]:
    """Return the bundle arguments *cls* accepts on top of its fields.

    A plot can be configured by concern rather than by keyword - ``annotation=Annotation(...)``
    instead of four ``annotate_*`` arguments - which a validator spreads into the fields.
    Those arguments are not fields, so they have to be read off ``option_bundles`` rather
    than off ``model_fields``.
    """
    bundles: dict[str, type] = getattr(cls, "option_bundles", {})
    return [Parameter(name, f"{bundle.__name__} | None", "None") for name, bundle in bundles.items()]


def _bound_names(tree: ast.Module) -> set[str]:
    """Return the names a module binds through its imports, at any nesting level."""
    bound: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            bound.update(alias.asname or alias.name.split(".")[0] for alias in node.names)
    return bound


def _free_names(parameters: list[Parameter]) -> set[str]:
    """Return the non-builtin names the rendered parameters refer to."""
    used: set[str] = set()
    for parameter in parameters:
        for source in (parameter.annotation, parameter.default):
            if source is None:
                continue
            used.update(node.id for node in ast.walk(ast.parse(source, mode="eval")) if isinstance(node, ast.Name))
    return {name for name in used if not hasattr(builtins, name)}


def _import_statement(base: type, name: str) -> str | None:
    """Return how the module of *base* imports *name*, as an absolute statement."""
    tree = _module_tree(base)
    if tree is None:
        return None

    package = base.__module__.rsplit(".", 1)[0]
    for node in ast.walk(tree):
        if not isinstance(node, (ast.Import, ast.ImportFrom)):
            continue
        if not any((alias.asname or alias.name.split(".")[0]) == name for alias in node.names):
            continue
        if isinstance(node, ast.Import):
            return f"import {name}"
        # Relative imports have to be rebased, the statement lands in another package.
        module = node.module or ""
        return f"from {package + '.' + module if node.level else module} import {name}"
    return None


def missing_imports(cls: type[BaseModel], tree: ast.Module) -> list[str]:
    """Return the imports *cls*'s module still needs for its generated signature.

    A default such as ``LunaColours.SKY`` or an annotation such as ``FeatureClass`` is
    written verbatim, so the component module has to import the symbol even though it
    only ever appears inside the never-executed block. The statement is copied from
    whichever base class declares the field, so the import path stays the one the
    project uses.
    """
    needed = _free_names(signature(cls)) - _bound_names(tree)

    statements = []
    for name in sorted(needed):
        for base in cls.__mro__:
            statement = _import_statement(base, name)
            if statement is not None:
                statements.append(statement)
                break

    return statements


def render(cls: type[BaseModel]) -> str:
    """Render the full ``if TYPE_CHECKING`` block for *cls*."""
    parameters = signature(cls)
    # The block is never executed, so the rules about how a signature is written are
    # about calling it, not about this copy of it.
    noqa = "  # noqa: PLR0913" if len(parameters) > _MAX_ARGS_WITHOUT_NOQA else ""
    body = "".join(f"            {_render_parameter(p)}\n" for p in parameters)
    return (
        f"    if TYPE_CHECKING:\n"
        f"        {MARKER}\n"
        f"        # Mirrors the pydantic fields so IDEs show every option on the constructor.\n"
        f"        # Never executed: pydantic builds the real ``__init__``.\n"
        f"        def __init__({noqa}\n"
        f"            self,\n"
        f"            *,\n"
        f"{body}"
        f"        ) -> None: ...\n"
    )


def _render_parameter(parameter: Parameter) -> str:
    """Render one parameter as it is written in the signature.

    A default that is a mutable literal is safe here - pydantic copies it per instance,
    and this signature is never executed - so the rule against it is silenced on the line
    it is reported on. The calls are exempted project-wide instead, in ``ruff.toml``.
    """
    # Ruff reads the rendered line, so a default the formatter will wrap has to carry its
    # exemption on the line the call starts on.
    default = "" if parameter.default is None else f" = {parameter.default}"
    noqa = "  # noqa: B006" if parameter.default in _COPIED_DEFAULTS else ""
    return f"{parameter.name}: {parameter.annotation}{default},{noqa}"


def _class_def(tree: ast.Module, name: str) -> ast.ClassDef:
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name == name:
            return node
    msg = f"class {name} not found"
    raise LookupError(msg)


def _generated_block(class_def: ast.ClassDef) -> ast.If | None:
    """Return the ``if TYPE_CHECKING`` block this script owns, if it is already there."""
    for node in class_def.body:
        if isinstance(node, ast.If) and any(
            isinstance(child, ast.FunctionDef) and child.name == "__init__" for child in node.body
        ):
            return node
    return None


def _insertion_line(class_def: ast.ClassDef) -> int:
    """Return the 0-based line the block goes on: right before the first method."""
    for node in class_def.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            starts = [node.lineno, *(d.lineno for d in node.decorator_list)]
            return min(starts) - 1
    return class_def.end_lineno or class_def.lineno


def _with_imports(lines: list[str], tree: ast.Module, statements: list[str]) -> list[str]:
    """Add *statements* to the module-level ``if TYPE_CHECKING`` block, creating it if needed."""
    last_import = max(
        (node.end_lineno or node.lineno) for node in tree.body if isinstance(node, (ast.Import, ast.ImportFrom))
    )

    # The generated block itself needs the flag, which a module without type-only
    # imports does not have yet.
    if "TYPE_CHECKING" not in _bound_names(tree):
        lines.insert(last_import, "from typing import TYPE_CHECKING\n")
        last_import += 1

    if not statements:
        return lines

    for node in tree.body:
        if isinstance(node, ast.If) and ast.unparse(node.test) == "TYPE_CHECKING":
            insert_at = node.body[0].lineno - 1
            break
    else:
        lines.insert(last_import, "\nif TYPE_CHECKING:\n")
        insert_at = last_import + 2

    lines[insert_at:insert_at] = [f"    {statement}\n" for statement in statements]
    return lines


def _formatted(path: Path, source: str) -> str:
    """Return *source* with imports sorted and formatted the way the project writes them."""
    for command in (["ruff", "check", "--fix-only", "--select", "I"], ["ruff", "format"]):
        result = subprocess.run(  # noqa: S603
            [*command, "--stdin-filename", str(path), "-"],
            check=True,
            capture_output=True,
            text=True,
            input=source,
            cwd=REPO_ROOT,
        )
        source = result.stdout
    return source


def updated_source(cls: type[BaseModel]) -> tuple[Path, str]:
    """Return the module of *cls* and its source with the generated signature written in."""
    path = Path(inspect.getfile(cls))
    lines = path.read_text().splitlines(keepends=True)
    tree = ast.parse("".join(lines))
    class_def = _class_def(tree, cls.__name__)

    existing = _generated_block(class_def)
    if existing is not None:
        start, end = existing.lineno - 1, existing.end_lineno or existing.lineno
        # The block is followed by a blank line that belongs to it.
        while end < len(lines) and not lines[end].strip():
            end += 1
        lines[start:end] = [render(cls), "\n"]
    else:
        lines.insert(_insertion_line(class_def), render(cls) + "\n")

    lines = _with_imports(lines, tree, missing_imports(cls, tree))
    return path, _formatted(path, "".join(lines))


def main(argv: list[str] | None = None) -> int:
    """Rewrite the generated signatures, or report the components that are out of date."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="only report outdated signatures")
    args = parser.parse_args(argv)

    components = component_classes()
    outdated: list[str] = []
    for cls in components:
        path, source = updated_source(cls)
        if source == path.read_text():
            continue
        outdated.append(f"{cls.__name__} ({path.relative_to(REPO_ROOT)})")
        if not args.check:
            path.write_text(source)

    if outdated and args.check:
        print("Outdated __init__ signatures, run 'uv run python scripts/type_hints.py':")  # noqa: T201
        print("\n".join(f"  {entry}" for entry in outdated))  # noqa: T201
        return 1

    print(f"{'Outdated' if args.check else 'Updated'}: {len(outdated)} of {len(components)} components")  # noqa: T201
    return 0


# Kept so the module stays importable: the test reuses the functions above, and a bare
# call here would rewrite the sources on import.
if __name__ == "__main__":
    raise SystemExit(main())
