from luna_quantum.solve.interfaces.algorithm_i import IAlgorithm
from luna_quantum.solve.interfaces.backend_i import IBackend
from luna_quantum.transformations import Pipeline

from luna_bench.components import ModelSet
from luna_bench.components.job import Job
from luna_bench.components.metric import Metric
from luna_bench.components.model_metric import ModelMetric


class Pipeline:
    @staticmethod
    def create(name: str) -> Pipeline: ...

    @staticmethod
    def import_from_file(file_path: str) -> Pipeline: ...

    def delete(self) -> None: ...

    @staticmethod
    def load(name: str) -> Pipeline: ...

    @staticmethod
    def load_all() -> list[Pipeline]: ...

    def run(self) -> None: ...

    def reset(self) -> None: ...

    def export_to_file(self, file_path: str) -> None: ...

    @property
    def modelset(self) -> ModelSet: ...

    @modelset.setter
    def modelset(self, value: ModelSet) -> None: ...

    def add_model_metric(self, model_metric: ModelMetric) -> None: ...
    def remove_model_metric(self, model_metric: ModelMetric) -> None: ...
    def list_model_metrics(self) -> list[ModelMetric]: ...
    def reset_model_metrics(self) -> None: ...

    def add_metric(self, metric: Metric) -> None: ...
    def remove_metric(self, metric: Metric) -> None: ...
    def list_metrics(self) -> list[Metric]: ...
    def reset_metrics(self) -> None: ...

    def add_job(self, algorithm: IAlgorithm, backend: IBackend | None = None) -> None: ...
    def remove_job(self, algorithm: IAlgorithm, backend: IBackend | None = None) -> None: ...
    def list_jobs(self) -> list[Job]: ...
    def reset_jobs(self) -> None: ...

    def run_model_metrics(self) -> None: ...
    def run_metrics(self) -> None: ...
    def run_plots(self) -> None: ...
    def run_jobs(self) -> None: ...
