name: "Lint & Test Template"
on:
  workflow_call:
    inputs:
      runner-type:
        required: true
        type: string
        description: 'The runner to use (self-hosted or ubuntu-latest)'
      timeout-minutes:
        required: false
        type: number
        default: 1
        description: 'Timeout in minutes'
      title-suffix:
        required: false
        type: string
        default: ''
        description: 'Suffix for coverage comment title'

jobs:
  lint-test:
    name: "Linting{{ inputs.title-suffix }}"
    runs-on: ${{ inputs.runner-type }}
    timeout-minutes: ${{ inputs.timeout-minutes }}

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Install uv"
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: "Set up Python"
        run: uv python install

      - name: "Install the project"
        run: uv sync --locked --all-extras --dev

      - name: "Ruff (Linter)"
        run: uv run ruff check --config ruff.toml

      - name: "Ruff (Formater)"
        run: uv run ruff format --check --config ruff.toml

      - name: "Mypy (Type checking)"
        run: uv run mypy --config-file .mypy.ini ./
