name: "PR Code Analysis"
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      runner-type:
        description: 'Choose where to run the workflow'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - 'self-hosted'
          - 'ubuntu-latest'

jobs:
  lint:
    name: "Lint"
    uses: ./.github/workflows/lint-template.yml
    with:
      runner-type: ${{ github.event.inputs.runner-type || 'ubuntu-latest' }}
  test:
    name: "Test"
    uses: ./.github/workflows/test-template.yml
    with:
      runner-type: ${{ github.event.inputs.runner-type || 'ubuntu-latest'  }}