name: "PR Code Analysis"
on:
  pull_request:
    branches:
      - main

jobs:
  choose-runner:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.runner.outputs.runner }}
    steps:
      - id: runner
        run: |
          if [ "${{ github.actor }}" == "ianpurton" ]; then
            echo "runner=self-hosted" >> $GITHUB_OUTPUT
          else
            echo "runner=ubuntu-latest" >> $GITHUB_OUTPUT
          fi

  lint:
    name: "Lint"
    needs: [ choose-runner ]
    uses: ./.github/workflows/lint-template.yml
    with:
      runner-type: ${{ needs.choose-runner.outputs.runner }}
      timeout-minutes: 5
      title-suffix: ""

  test:
    name: "Test"
    needs: [ choose-runner ]
    uses: ./.github/workflows/test-template.yml
    with:
      runner-type: ${{ needs.choose-runner.outputs.runner }}
      timeout-minutes: 5
      title-suffix: ""
